# Generated by Django 5.1.7 on 2025-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
